### ISSUE TITLE
Control character causing character mapping issue on Windows

### ISSUE THREAD

**Issue by padhia** [tdcoa/sql#1]
https://github.com/tdcoa/sql/blob/9d45dbaa6b52257e68bf4c3d4ac43692376822b7/filesets/top_users/top_users.py#L127

The line referenced above contains a Unicode character https://www.fileformat.info/info/unicode/char/2663/index.htm that cannot be translated to Latin based Windows codepage 1252. Most likely this is a typo and the intended character sequence is `$a$`.

PS: Originally reported by Kelsie Fritschie.

**Comment by tdcoa** [comment]
Kailash, In "top_users.py" i made the change to remove the unicode character "$♣$", and replace it with "$a$", which matches the alpha pattern behind it.   I also  added "$f$" which was  missing from the alphabet pattern as well.   i.e, line 127 - 129 now looks like this:

    markers_unique_list = ["D", "X", "H", "s", "P", "*", "v", "^", "o", "d", "h", "$f$", "<", ">", "$a$", "$b$", "$c$",
                           "$d$", "$e$", "$f$", "$g$", "$h$", "$i$", "$j$", "$k$", "$l$", "$m$", "$n$", "$o$", "$p$", "$q$",
                           "$r$", "$s$", "$t$", "$u$", "$v$", "$w$", "$x$", "$y$", "$z$"]

Please review and let us know whether this was OK or not.   The special character was breaking Windows OS.  Thx!

**Comment by tdcoa** [comment]
I changed this some time ago, but forgot to close the issue.  done!
